### ISSUE TITLE
not adding users

### ISSUE THREAD

**Issue by ShemShadrack** [AbirHasan2005/TelegramScraper#11]

**Comment by ShemShadrack** [comment]
the bot is scraping member but when it comes to adding them in the channel its not working  i did even leave the bot run for a day but it didnt work

**Comment by AbirHasan2005** [comment]
Send Traceback.

**Comment by ShemShadrack** [comment]
i figured it out is the a way in the script to reduce time it takes to add users as mine is taking about 30min or more per user imagine if there a 100 members in the members.csv it means i would have to leave my comp on  for the whole day so as to finish adding users

**Comment by AbirHasan2005** [comment]
#BlameTelegram
We can't do anything if Telegram not allows us to do. They will send FloodWait which no one can bypass.
