### ISSUE TITLE
Flood error

### ISSUE THREAD

**Issue by ZetOnline** [AbirHasan2005/TelegramScraper#13]
Thanks for this software but i cant solve the problem with flood, after 10 or 15 request give a error by flood. Is impossible to avoid this?

I change time request to 5 min, but persist

After the error appear, is possible resume? To avoid send message to same users again

**Comment by AbirHasan2005** [comment]
This is telegram side issue. We can't do anything. Hope works fine in fresh new account.

**Comment by Suniron** [comment]
Hmmm its seem to be the same for me :'(.

It's a new Telegram limitation, right ?

**Comment by AbirHasan2005** [comment]
Nope this limitation is old.
