### ISSUE TITLE
Customize group list...

### ISSUE THREAD

**Issue by XMVZ** [AbirHasan2005/TelegramScraper#15]
When I run scraper.py it gives me a preloaded list of groups to choose from..
How do I add my own groups to the list as the ones listed are not of interest.

Thank you!

**Comment by XMVZ** [comment]
I think I figured this out..
Also, how should the members.csv be formatted?

Running into this error:
![Screenshot_123](https://user-images.githubusercontent.com/79497004/132078168-50eab346-6ec3-4d59-810f-a12c024d6b1a.png)

Thanks!

**Comment by XMVZ** [comment]
Also getting this in the setup.py:
![Screenshot_125](https://user-images.githubusercontent.com/79497004/132078336-5fc6799d-12f7-4ac2-b71f-eedd5fdd4d14.png)

Sorry for slamming you with questions!

Thanks!

**Comment by XMVZ** [comment]
What line should I add to the setup.py code to have touch installed?
I was able to fix the error by running "npm install touch-cli -g" but I'd like to add it to the script.

**Comment by XMVZ** [comment]
And finally!
![Screenshot_126](https://user-images.githubusercontent.com/79497004/132078483-b90f5c3b-0ee4-4e57-ae93-ede6f8a937b7.png)

**Comment by XMVZ** [comment]
I was able to get the script to work for a bit.. but now I am getting FLOOD ERROR, TRY AGAIN IN 100 SECONDS. Any time I run the script, this occurs. Can anyone help me out?

**Comment by AbirHasan2005** [comment]
> I was able to get the script to work for a bit.. but now I am getting FLOOD ERROR, TRY AGAIN IN 100 SECONDS. Any time I run the script, this occurs. Can anyone help me out?

It's Telegram side issue. Make new fresh Telegram account for avoiding huge FloodWaits.
