### ISSUE TITLE
scraper dosent work 

### ISSUE THREAD

**Issue by AliSat81** [AbirHasan2005/TelegramScraper#19]
[+] Enter a Number: 0
[+] Fetching Members ...
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\TelegramScraper-master\scraper.py", line 85, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)')], [<telethon.tl.types.channels.ChannelParticipants object at 0x0000021B6D103D00>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000021B6CB00430>, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000021B6D0FDA00>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF280>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF340>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF400>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF4C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF580>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF640>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF700>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF7C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF880>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FF940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFA00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFAC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFB80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFC40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFD00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFDC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFE80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C7FFF40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804040>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804100>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C8041C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804280>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804340>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804400>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C8044C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000021B6C804580>])

**Comment by hardcore** [comment]
Hello! I got the same issue a since a few days ago. Maybe something changed in API?

**Comment by AliSat81** [comment]
> Hello! I got the same issue a since a few days ago. Maybe something changed in API?

Hey! I found somthing for scraper 😁.
Now I looking for scrypt of channel adder .


[Use this for scraper 😉](https://github.com/erfan4lx/Telegram-Channel-Member-Scraper)

**Comment by Senarock** [comment]
So what is the solution??????

**Comment by AliSat81** [comment]
> So what is the solution??????

Hey! 
Do you mean channel adder? I didn't find the solution to that.
You can add users to the group only if you have interacted with them before, but I had no idea about adding them to the channel.

**Comment by AbirHasan2005** [comment]
Use Telegram Bot for Scraping and Adding.
Username - [@MembersScraperBot](https://t.me/MembersScraperBot)
