### ISSUE TITLE
Telegram scraper not working

### ISSUE THREAD

**Issue by Aakash91225** [AbirHasan2005/TelegramScraper#31]
![Screenshot_20220816-104351.png](https://user-images.githubusercontent.com/111223847/184804073-c4313642-7116-4fc0-aa62-39851342d097.png)

**Comment by AbirHasan2005** [comment]
Use [@MembersScraperBot](https://t.me/MembersScraperBot)

**Comment by Aakash91225** [comment]
![Screenshot_20220817-141048.png](https://user-images.githubusercontent.com/111223847/185075442-3213902f-6feb-46eb-9921-c74355c2eb07.png)










Not working
