### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Muratbaev** [AbirHasan2005/TelegramScraper#4]
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TelegramScraper/adder.py", line 44, in <module>
    with open(r"members.csv", encoding='UTF-8') as f:  #Enter your file name
FileNotFoundError: [Errno 2] No such file or directory: 'members.csv'`

**Comment by AbirHasan2005** [comment]
This is because you deleted some files while it is processing.
