### ISSUE TITLE
smsbot.py linebreak possible? 

### ISSUE THREAD

**Issue by hardcore** [AbirHasan2005/TelegramScraper#8]
Hello!

Is it possible in the 2nd line of the smsbot.py "[+] Enter Your Message :" to enter more than 1 line?

Thanks
hc :)

**Comment by AbirHasan2005** [comment]
I will try.

**Comment by hardcore** [comment]
Did you had some time to try? :)

**Comment by hardcore** [comment]
Push :-)

**Comment by AbirHasan2005** [comment]
> Push :-)

You can do via `\n` for line break.

**Comment by hardcore** [comment]
Thanks for the tip! I tryed that in the past with \n but in Telegram I just see the \n and no line break.

See screenshots:

<img width="515" alt="Bildschirmfoto 2021-08-10 um 16 40 19" src="https://user-images.githubusercontent.com/58683/128887433-76fcec7f-b301-4b6e-a387-125fb349ecc8.png">
<img width="675" alt="Bildschirmfoto 2021-08-10 um 16 40 52" src="https://user-images.githubusercontent.com/58683/128887454-7ae5be90-64a9-4cab-ae15-d8e7178322cc.png">


Thanks a lot!

**Comment by hardcore** [comment]
Thanks a lot!
